# Generated by Django 5.2.6 on 2025-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_registration_alter_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='add',
            field=models.TextField(default=''),
        ),
    ]
